/**
 * Metadata helpers for the `[locale]` layout and pages, the sitemap, the JSON-LD and the
 * generated images. Everything is derived from the locale's content and the site config.
 *
 * Server-side by convention (it reads `@/content`): don't import it from client components.
 */
import type { Metadata } from "next";

import { formatMessage, getContent, getProfileMessageValues, type Profile } from "@/content";
import {
  DEFAULT_LOCALE,
  SITE_URL,
  SUPPORTED_LOCALES,
  toLanguageTag,
  toOpenGraphLocale,
  type Locale,
} from "@/shared/config/site";
import { getSitePagePath, type SitePage } from "@/shared/config/site-links";

/**
 * Theme tokens from src/app/globals.css (`:root`), as hex: generated images, the manifest
 * and the viewport's theme color can't read CSS variables. Update both places together;
 * tests/seo-brand-colors.test.ts fails when they drift apart.
 */
export const BRAND_COLORS = {
  canvas: "#F6F6F7",
  surface: "#FFFFFF",
  ink: "#1F2328",
  muted: "#595F68",
  line: "#E2E3E6",
  strong: "#1F2328",
  onStrong: "#FFFFFF",
} as const;

/** Sizes of the images generated by src/app/[locale]/opengraph-image.tsx, icon.tsx and apple-icon.tsx. */
export const OG_IMAGE_SIZE = { width: 1200, height: 630 };
export const ICON_SIZE = { width: 192, height: 192 };
export const APPLE_ICON_SIZE = { width: 180, height: 180 };

/** Absolute URL of a page, e.g. `https://example.com/en/about`. */
export function getPageUrl(locale: Locale, page: SitePage): string {
  return `${SITE_URL}${getSitePagePath(locale, page)}`;
}

/** hreflang alternates of a page: every supported locale plus `x-default` (the default locale). */
export function getLanguageAlternates(page: SitePage): Record<string, string> {
  const languages: Record<string, string> = {};
  for (const locale of SUPPORTED_LOCALES) {
    languages[toLanguageTag(locale)] = getPageUrl(locale, page);
  }
  languages["x-default"] = getPageUrl(DEFAULT_LOCALE, page);
  return languages;
}

/** `seo.title`, or "<name> — <headline>". Used as the home page title. */
export function getSiteTitle(profile: Profile): string {
  return profile.seo?.title?.trim() || `${profile.person.name} — ${profile.person.headline}`;
}

/** `seo.description`, or the introduction summary. */
export function getSiteDescription(profile: Profile): string {
  return profile.seo?.description?.trim() || profile.person.summary;
}

/** Alt text of the generated Open Graph image (it shows the name and the headline). */
export function getOgImageAlt(profile: Profile): string {
  return `${profile.person.name} — ${profile.person.headline}`;
}

/**
 * Initials for the generated app icons, at most two: "Jordan Rivera" → "JR",
 * "Madonna" → "M", "Ana María de la Cruz" → "AC". Words without a letter or digit
 * (emoji, punctuation) are skipped.
 */
export function getMonogram(name: string): string {
  const initials = name
    .normalize("NFC")
    .split(/\s+/)
    .map((word) => word.match(/[\p{L}\p{N}]/u)?.[0])
    .filter((initial): initial is string => Boolean(initial));
  const picked = initials.length > 1 ? [initials[0], initials[initials.length - 1]] : initials;
  // toUpperCase() can expand a letter ("ß" → "SS"); keep one character per initial.
  return picked.map((initial) => Array.from(initial.toUpperCase())[0]).join("");
}

/**
 * Canonical URL, hreflang alternates and social cards of one page. Pages set these
 * fields completely because Next.js merges metadata shallowly: a page-level `openGraph`
 * replaces the layout's instead of extending it.
 */
function buildSharedMetadata(
  locale: Locale,
  page: SitePage,
  title: string,
  description: string
): Pick<Metadata, "alternates" | "openGraph" | "twitter"> {
  const profile = getContent(locale).profile;
  const url = getPageUrl(locale, page);
  // Explicit because file-based images only reach the segment that holds the file.
  const image = {
    url: `${getPageUrl(locale, "")}/opengraph-image`,
    ...OG_IMAGE_SIZE,
    alt: getOgImageAlt(profile),
    type: "image/png",
  };
  const alternateLocale = SUPPORTED_LOCALES.filter((other) => other !== locale).map(toOpenGraphLocale);

  return {
    alternates: { canonical: url, languages: getLanguageAlternates(page) },
    openGraph: {
      type: "website",
      siteName: profile.person.name,
      locale: toOpenGraphLocale(locale),
      ...(alternateLocale.length > 0 ? { alternateLocale } : {}),
      url,
      title,
      description,
      images: [image],
    },
    twitter: { card: "summary_large_image", title, description, images: [image] },
  };
}

/** Metadata for `src/app/[locale]/layout.tsx` (`generateMetadata`). */
export function buildRootMetadata(locale: Locale): Metadata {
  const { profile, messages } = getContent(locale);
  const title = getSiteTitle(profile);
  const description = getSiteDescription(profile);
  const keywords = profile.seo?.keywords ?? [];

  return {
    metadataBase: new URL(SITE_URL),
    title: {
      default: title,
      // "{page} · {name}" → "%s · <name>"; Next.js puts each child page's `title` in place of %s.
      template: formatMessage(messages.meta.pageTitle, {
        ...getProfileMessageValues(profile),
        page: "%s",
      }),
    },
    description,
    ...(keywords.length > 0 ? { keywords } : {}),
    // The bundled example profile must never end up in search results.
    robots: profile.isExample ? { index: false, follow: false } : { index: true, follow: true },
    ...buildSharedMetadata(locale, "", title, description),
  };
}

export type PageMetadataArgs = {
  locale: Locale;
  page: SitePage;
  /**
   * The plain, localized page name (e.g. `messages.about.title`); the root title template
   * adds the owner's name. Omit it on the home page, which uses the default title.
   */
  title?: string;
  /** Defaults to the site description. */
  description?: string;
};

/** Metadata for a page under `[locale]` (`generateMetadata`). */
export function buildPageMetadata({ locale, page, title, description }: PageMetadataArgs): Metadata {
  const { profile, messages } = getContent(locale);
  const pageDescription = description?.trim() || getSiteDescription(profile);
  // Social cards don't get the title template, so they use the full title.
  const socialTitle = title
    ? formatMessage(messages.meta.pageTitle, { ...getProfileMessageValues(profile), page: title })
    : getSiteTitle(profile);

  return {
    // Set only when given: an explicit `undefined` would replace the inherited value.
    ...(title ? { title } : {}),
    description: pageDescription,
    ...buildSharedMetadata(locale, page, socialTitle, pageDescription),
  };
}
